# Generated by Django 3.2.12 on 2022-03-31 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f1', models.IntegerField(default=1)),
                ('f2', models.IntegerField(default=2)),
                ('f3', models.IntegerField(default=3)),
                ('f4', models.IntegerField(default=4)),
                ('f5', models.IntegerField(default=5)),
                ('f6', models.IntegerField(default=6)),
                ('f7', models.IntegerField(default=7)),
                ('f8', models.IntegerField(default=8)),
                ('f9', models.IntegerField(default=9)),
                ('f10', models.IntegerField(default=10)),
            ],
        ),
    ]
