# Generated by Django 3.2.12 on 2022-04-01 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exampleapp', '0002_child_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='BinaryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.BinaryField()),
            ],
        ),
    ]
