# Generated by Django 3.2.12 on 2022-04-04 22:48

import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
import django.contrib.postgres.fields.ranges
from django.db import migrations, models
from django.contrib.postgres.operations import HStoreExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        HStoreExtension(),
        migrations.CreateModel(
            name='PostgresFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int1d', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), null=True, size=None)),
                ('int2d', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), null=True, size=None), null=True, size=None)),
                ('txt1d', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32, null=True), null=True, size=None)),
                ('txt2d', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32, null=True), null=True, size=None), null=True, size=None)),
                ('hstore', django.contrib.postgres.fields.hstore.HStoreField(null=True)),
                ('int_r', django.contrib.postgres.fields.ranges.IntegerRangeField(null=True)),
                ('dt_r', django.contrib.postgres.fields.ranges.DateTimeRangeField(null=True)),
                ('date_r', django.contrib.postgres.fields.ranges.DateRangeField(null=True)),
            ],
        ),
    ]
