# Generated by Django 3.2.12 on 2022-04-06 13:59

import datetime
from decimal import Decimal
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('postgres_tests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldUpdateNotNull',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_biginteger', models.BigIntegerField(default=0)),
                ('f_binary', models.BinaryField(default=b'')),
                ('f_boolean', models.BooleanField(default=False)),
                ('f_char', models.CharField(default='', max_length=32)),
                ('f_date', models.DateField(default=datetime.date(1000, 1, 1))),
                ('f_datetime', models.DateTimeField(default=datetime.datetime(1000, 1, 1, 0, 0))),
                ('f_decimal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('f_duration', models.DurationField(default=datetime.timedelta(1))),
                ('f_email', models.EmailField(default='', max_length=254)),
                ('f_float', models.FloatField(default=0.0)),
                ('f_integer', models.IntegerField(default=0)),
                ('f_ip', models.GenericIPAddressField(default='')),
                ('f_json', models.JSONField(default=dict)),
                ('f_slug', models.SlugField(default='')),
                ('f_smallinteger', models.SmallIntegerField(default=0)),
                ('f_text', models.TextField(default='')),
                ('f_time', models.TimeField(default=datetime.time(1, 0))),
                ('f_url', models.URLField(default='')),
                ('f_uuid', models.UUIDField(default=uuid.UUID('5e0b7757-b58e-40c2-b305-a35912b4a43a'))),
            ],
        ),
    ]
