# Generated by Django 3.2.12 on 2022-04-10 20:16

import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('postgres_tests', '0004_auto_20220407_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hstore', django.contrib.postgres.fields.hstore.HStoreField()),
                ('int_r', django.contrib.postgres.fields.ranges.IntegerRangeField()),
                ('int_2d', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=1), size=None), size=None)),
                ('hstore_2d', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.hstore.HStoreField(), size=None), size=None)),
                ('int_r_2d', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ranges.IntegerRangeField(), size=None), size=None)),
            ],
        ),
        migrations.AlterField(
            model_name='fieldupdatenotnull',
            name='f_uuid',
            field=models.UUIDField(default=uuid.UUID('759fe50b-9881-47d8-8cb9-85646f37cba0')),
        ),
    ]
